Clean up unneeed includes
ashirt-ops/ashirt pull request #185
Opened 2022-06-30 15:57 UTC by crizzitello

Clean up unneeded includes
Remove std::err and std::cout for Qt methods

2022-06-30 16:44 UTC, JoelAtDeluxe submitted a review, later dismissed
Looks good.

As an aside, I wonder if we should keep around the CLI portion of the application (which currently does next-to-nothing). Originally, I think we might have wanted to support CLI-only type environments, but I suspect that's unlikely to be useful in practice.

2022-06-30 19:10 UTC, jkennedyvz submitted a review, later dismissed

2022-07-02 07:33 UTC, jrozner approved these changes

2022-07-02 07:37 UTC, jrozner requested changes
I didn't end up marking all of them but it seems like most of the output here are errors but they are going to stdout. Should these get updated to stderr?

2022-07-02 07:37 UTC, jrozner commented on src/forms/evidence/evidencemanager.cpp
> +    QTextStream(stdout) << "Could not refresh table row: " << e.text() << Qt::endl;
should this be stderr?

2022-07-02 07:37 UTC, jrozner commented on src/forms/evidence/evidencemanager.cpp
> +      QTextStream(stdout) << "Upload failed. Could not update internal database. Error: "
stderr?

2022-07-02 07:37 UTC, jrozner commented on src/forms/getinfo/getinfo.cpp
> +      QTextStream(stdout) << "Upload failed. Could not update internal database. Error: "
stderr?

2022-07-02 07:37 UTC, jrozner commented on src/forms/getinfo/getinfo.cpp
> +      QTextStream(stdout) << "Upload successful. Could not update internal database. Error: "
stderr?

2022-07-05 14:50 UTC, crizzitello commented
Updated with more unneeded includes removed also using std err for most of the TextStreams.

2022-07-05 16:36 UTC, jrozner reviewed
Changes look good

2022-07-05 16:36 UTC, jrozner commented on src/components/error_view/errorview.h
> +//#include <QLabel>
Is this supposed to be commented out with the forward class declaration below?

2022-07-05 16:36 UTC, jrozner commented on src/helpers/netman.h
> +//#include "helpers/file_helpers.h"
Is this just not needed?

2022-07-05 16:36 UTC, jrozner commented on src/traymanager.cpp
> +    QTextStream(stdout) << "could not write to the database: " << e.text() << Qt::endl;
Should this be stderr?

2022-07-06 02:17 UTC, jrozner approved these changes

2022-07-06 19:44 UTC, merged