Use QDir to store/render paths (over custom solution)
ashirt-ops/ashirt pull request #39
Opened 2020-08-14 18:58 UTC by JoelAtDeluxe

This PR removes the previous PATH_SEPARATOR variable and file, in place of the native Qt solution of QDir::toNativePath and QDir::fromNativePath (in addition to Qt's default handling of `/` as the path separator). In effect, this PR will always show the native path separator to the user, while always using `/` internally to represent the path.

Addresses Issue #32 

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2020-09-10 20:40 UTC, jkennedyvz submitted a review, later dismissed
Hi Joel,

Thanks for these updates.

2020-09-11 01:02 UTC, jrozner requested changes
Changes look good. While we're here and finalizing the default settings can we setup the default value of the evidence repo to be in `QStandardPaths::DataLocation + "/evidence"` since we're migrating the paths around here anyway. I'd like to avoid multiple breaking change PRs if we can to get it into the final state.

There's some manual index("/") that I'd like to circle back to at some point to use QDir to manage but for now this should be fine. I have a half done branch that does some of this but it was a much more involved set of changes and I didn't get around to finishing them. Let's go ahead and merge this once we move the paths over.

2020-09-11 01:02 UTC, jrozner commented on src/appconfig.h
> +      QStandardPaths::writableLocation(QStandardPaths::ConfigLocation) + "/ashirt/config.json";
This should use QStandardPaths::DataLocation. This is the same problem as in aterm where ConfigLocation points to Preferences which is for the macos managed plists rather than application specific config files.

2020-09-11 01:02 UTC, jrozner commented on src/db/databaseconnection.h
> +    QStandardPaths::writableLocation(QStandardPaths::ConfigLocation) + "/ashirt/evidence.sqlite";
Same as above

2020-09-11 15:26 UTC, JoelAtDeluxe commented on src/appconfig.h
> +      QStandardPaths::writableLocation(QStandardPaths::ConfigLocation) + "/ashirt/config.json";
based on the docs, I think dataLocation is going to be:
`~/Library/Application Support/AShirt Screenshot` (as the docs indicate that the `APPNAME` will be used). Should we update the APPNAME to be something else?

2020-09-11 15:55 UTC, JoelAtDeluxe commented
Just an observation: if everything is using DataLocation as a base, then everything is going to be under the same directory. On OSX, that'll look like:
```
/Users/jrozner/Library/Application Support/AShirt Screenshot/
├── config.json
├── evidence
└── evidence.sqlite
```

I suppose we'll place ATerm at:
`/Users/jrozner/Library/Application Support/ATerm` and have similar layout?

2020-09-11 16:18 UTC, jrozner commented on src/appconfig.h
> +      QStandardPaths::writableLocation(QStandardPaths::ConfigLocation) + "/ashirt/config.json";
Ya, I think that makes sense. I had already done that in the branch I was working on but forgot it wasn't in master. The following changes should be made to `src/main.cpp`:

```diff
-  QCoreApplication::setOrganizationName("Verizon Media Group");
-  QCoreApplication::setOrganizationDomain("verizon.com");
-  QCoreApplication::setApplicationName("AShirt Screenshot");
+  QCoreApplication::setApplicationName("ashirt");
```

2020-09-11 16:20 UTC, jrozner commented
re: aterm and ashirt, I commented on that in the big aterm PR about this. I think it makes sense.

2020-09-11 23:24 UTC, jrozner approved these changes

2020-09-11 23:26 UTC, merged